backend:
  name: github
  branch: main
  repo: 'institutoazmina/penhas-www'
  base_url: https://sveltia-cms-auth.azmina-rootaccount.workers.dev
media_folder: static/img
public_folder: /img
collections:
  - name: 'testimonials'
    label: 'Testimonial'
    folder: 'content/testimonials'
    create: true
    slug: '{{slug}}'
    identifier_field: 'reviewer.name'
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - label: 'Reviewer'
        name: 'reviewer'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'name', widget: 'string'  }
          - { label: 'Role', name: 'role', widget: 'string', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
  - name: 'timeline'
    label: 'Timeline'
    folder: 'content/timeline'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Title', name: 'title', widget: 'string' }
      - default: 0
        name: 'year'
        label: 'year'
        required: true
        widget: 'number'
      - default: 0
        name: 'month'
        label: 'month'
        widget: 'number'
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'figure'
        widget: object
        fields:
          - { label: File, name: file, widget: 'image' }
          - { label: Description, name: description, widget: 'string', required: true }
  - name: 'team'
    label: 'Team member'
    folder: 'content/team'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Biography', name: 'body', widget: 'markdown' }
      - name: 'picture'
        widget: object
        fields:
          - { label: File, name: file, widget: 'image' }
          - { label: Description, name: description, widget: 'string', required: true }
      - label: 'Role'
        name: 'role'
        widget: 'select'
        options:
          - { label: 'Super chefa', value: 'super_chefa' }
          - { label: 'Chefa', value: 'chefa' }
          - { label: 'Chefa master', value: 'chefa_master' }
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - name: 'thumbnail'
        label: 'Thumbnail'
        widget: object
        fields:
          - { label: File, name: file, widget: 'image' }
          - { label: Description, name: description, widget: 'string', required: true }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'media'
    label: 'Media'
    folder: 'content/media'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Permalink'
        name: 'permalink'
        widget: 'string'
        hint: 'https://...'
        pattern: ['^https://', 'Must be a valid URL']
      - name: 'thumbnail'
        label: 'Thumbnail'
        widget: object
        fields:
          - { label: File, name: file, widget: 'image' }
          - { label: Description, name: description, widget: 'string', required: true }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
  - name: 'feature'
    label: 'Feature'
    folder: 'content/features'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'figure'
        widget: object
        fields:
          - { label: File, name: file, widget: 'image' }
          - { label: Description, name: description, widget: 'string', required: true }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
  - name: 'data'
    label: 'Data Files'
    files:
      - name: 'bigNumber'
        label: 'Big numbers'
        file: 'data/big_numbers.yaml'
        summary: '{{fields.description}}'
        fields:
          - name: number
            collapsed: true
            label: Numbers
            label_singular: Number
            root: true
            widget: list
            fields:
              - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
              - { label: 'Value', name: 'value', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
      - label: 'Sponsors'
        name: 'sponsors'
        file: 'data/sponsors.yaml'
        summary: '{{fields.name}}'
        fields:
          - name: sponsors
            collapsed: true
            label: Sponsors
            label_singular: Sponsor
            root: true
            widget: list
            fields:
              - label: 'draft'
                name: 'draft'
                default: true
                widget: 'boolean'
              - label: 'name'
                name: 'name'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                hint: 'https://...'
                pattern: ['^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(?:-nocookie)?\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|live\/|v\/)?)([\w\-]+)(\S+)?$', 'Must be a valid URL']
                required: false
                widget: 'string'
              - label: 'logotype'
                name: 'logotype'
                widget: 'image'
              - default: 0
                name: 'weight'
                label: 'Weight'
                required: false
                widget: 'number'
      - name: 'params'
        label: 'Configurations'
        file: 'config/_default/params.yaml'
        fields:
          - { label: 'description', name: 'description', widget: 'string' }
          - label: 'Institutional video'
            name: 'institutionalVideo'
            widget: 'string'
            hint: 'https://...'
            pattern: ['^https://', 'Must be a valid URL']
            required: false
          - label: 'images'
            name: 'images'
            widget: 'list'
            fields:
              - label: 'file'
                name: 'file'
                widget: 'image'
          - label: 'Contact methods'
            name: 'contactMethods'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'select'
                options:
                  - { label: 'E-mail', value: 'email' }
                  - { label: 'Facebook', value: 'facebook' }
                  - { label: 'Instagram', value: 'instagram' }
                  - { label: 'Threads', value: 'threads' }
                  - { label: 'TikTok', value: 'tiktok' }
                  - { label: 'X', value: 'twitter' }
                  - { label: 'Youtube', value: 'youtube' }
              - label: 'Link'
                name: 'link'
                widget: 'string'
                pattern: ['^(https://)|', 'Must be a valid URL']
